{{ $htpasswdString := htpasswd .Values.admin.username .Values.admin.password -}}
{{ $htpasswdHash := split ":" $htpasswdString -}}

apiVersion: v1
kind: Secret
metadata:
  name: portainer-initial-credentials
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "portainer.selectorLabels" . | nindent 8 }}
data:
  username: {{ default "" .Values.admin.username | b64enc | quote }}
  password: {{ $htpasswdHash._1 | b64enc | quote }}