apiVersion: v1
kind: Service
metadata:
  name: {{ include "portainer-agent.fullname" . }}-headless
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portainer-agent.selectorLabels" . | nindent 4 }} 